import json
from agents import llm, safe_parse_json
from state import MarketMindState

def synthesis_agent(state: MarketMindState) -> dict:
    ticker = state["ticker"]
    signals = state.get("agent_signals", [])
    
    if not signals:
        return {
            "final_verdict": "NEUTRAL",
            "final_confidence": 0.0,
            "final_reasoning": "No signals were generated by the agents."
        }
        
    # Group signals for prompt
    signals_data = []
    for s in signals:
        signals_data.append({
            "agent": s["agent"],
            "signal": s["signal"],
            "confidence": s["confidence"],
            "summary": s["summary"]
        })
        
    prompt = f"""You are the lead portfolio manager. Review the analysis from your specialist agents for {ticker}:

{json.dumps(signals_data, indent=2)}

Synthesize these views into a final, unified trading verdict.
Weigh the confidence and reasoning of each agent.
Provide a clear final signal, an aggregate confidence score, and a brief reasoning summarizing the consensus or key conflicting points.

Return ONLY valid JSON with exactly these fields:
{{"final_verdict": "BULLISH" or "BEARISH" or "NEUTRAL", "final_confidence": 0.0 to 1.0, "final_reasoning": "2-3 sentences explaining the synthesized view"}}"""

    try:
        result_raw = llm.invoke(prompt)
        result = safe_parse_json(result_raw.content)
        
        return {
            "final_verdict": result["final_verdict"],
            "final_confidence": float(result["final_confidence"]),
            "final_reasoning": result["final_reasoning"]
        }
    except Exception as e:
         return {
            "final_verdict": "NEUTRAL",
            "final_confidence": 0.0,
            "final_reasoning": f"Synthesis agent error: {str(e)[:60]}"
        }
